name: newman tests
on:
  pull_request:
    branches: [master]

concurrency:
  group: newman-tests-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm i
        working-directory: newman
      - run: TESTOMATIO=m6ef70356h7cnpm run test
        working-directory: newman
