name: test
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REPOSITORY
      - run: echo ${{ github.workflow }}
      - run: TESTOMATIO=n7seb4fd0zg8 GH_PAT=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 GITHUB_REF=refs/pull/36/merge GITHUB_REPOSITORY=testomatio/examples npm run test animal-sort/
